framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: omm.gothick.org.uk

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        app: cache.adapter.redis
        # For dev/test environments, point to the "redis" service defined in docker-compose.yml
        # We use database index 1 for application cache as on our live server WordPress uses index 0
        # and it's nice to be consistent across environments.
        default_redis_provider: '%env(REDIS_URL)%'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        # app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
